site_name: BGE and Senior Phase Computing Science
nav:
    - Home: 'index.md'
    - S1:
      - Home: 'Homepages/2.0_S1_Home.md'
      - Turtle Programming: 'Levels/BGE/S1/Turtle_Programming/1.0_Home.md'
      - Hidden Tabs:
        - Introducing the Turtle: 'Levels/BGE/S1/Turtle_Programming/2.0_Introducing_the_Turtle.md'
        - Movement and Colour: 'Levels/BGE/S1/Turtle_Programming/3.0_Movement_and_Colour.md'
    - S2:
      - Home: 'Homepages/3.0_S2_Home.md'
      - Python Programming: 'Levels/BGE/S2/Python_Programming/1.0_Homepage.md'
        #- Introduction to Python: 'BGE/S2/Python_Programming/1.0_Intro_to_Python.md'
        #- Extra Credit Tasks: 'BGE/S2/Python_Programming/Extra_Credit_Tasks.md'
    - S3: 
      - Home: 'Homepages/4.0_S3_Home.md'
    - National 5:
      - Home: 'Homepages/5.0_L5_Home.md'
      - Unit 1 - Software Design and Development: 
        - Development Methodologies: 'Levels/Senior_Phase/Unit_1_SDD/1.0_Development_Methodologies/L5/5.0_Home.md'
        - Analysis: 'Levels/Senior_Phase/Unit_1_SDD/2.0_Analysis/L5/5.0_Home.md'
        - Design: 'Levels/Senior_Phase/Unit_1_SDD/3.0_Design/L5/5.0_Home.md'
        - Software Implementation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.0_Home.md'
        - Testing: 'Levels/Senior_Phase/Unit_1_SDD/5.0_Testing/L5/5.0_Home.md'
        - Evaluation: 'Levels/Senior_Phase/Unit_1_SDD/6.0_Evaluation/L5/5.0_Home.md'
      - Unit 2 - Computer Systems:
        - Data Representation: 'Levels/Senior_Phase/Unit_2_CS/1.0_Data_Representation/L5/5.0_Home.md'
        - Computer Architecture: 'Levels/Senior_Phase/Unit_2_CS/2.0_Computer_Architecture/L5/5.0_Home.md'
        - Security and Encryption: 'Levels/Senior_Phase/Unit_2_CS/3.0_Security_and_Encryption/L5/5.0_Home.md'
      - Hidden Tabs:
        - Input and Output: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.1_Input_and_Output.md'
        - Variables and Data Types: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.2_Variables_and_Data_Types.md'
        - Arrays: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.3_Arrays.md'
        - Simple Conditional Statements: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.4_Simple_Conditional_Statements.md'
        - Complex Conditional Statements: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.5_Complex_Conditional_Statements.md'
        - Fixed Loops(for): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.6_Fixed_Loops_(for).md'
        - Conditional Loops(while): 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.7_Conditional_Loops_(while).md'
        - Pre-Defined Functions: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.8_Pre_Defined_Functions.md'
        - Traversing a 1D Array: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.9_Traversing_a_1d_Array.md'
        - Running Total within a Loop: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.10_Running_Total_Within_a_Loop.md'
        - Input Validation: 'Levels/Senior_Phase/Unit_1_SDD/4.0_Software_Implementation/L5/5.11_Input_Validation.md'

      #- Computer Systems:
        #- Data Representation:
    - Higher:
      - Home: 'Homepages/6.0_L6_Home.md'
    - Advanced Higher: 
      - Home: 'Homepages/7.0_L7_Home.md'
    

markdown_extensions:
      - admonition
      - pymdownx.details
      - def_list
      - pymdownx.critic
      - pymdownx.caret
      - pymdownx.keys
      - pymdownx.mark
      - pymdownx.tilde
      - attr_list
      - md_in_html    
      - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
      - pymdownx.superfences
      - pymdownx.tabbed:
          alternate_style: true
      - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.snippets
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - navigation.path
    #- navigation.footer
    - navigation.tabs

copyright: Copyright &copy; 2025 Pixel&Wood Code Studio

extra_css:
  - styles/extra.css
extra_javascript:
  - scripts/extra.js
    

